# -*- coding: utf-8 -*-
"""yolov12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JrzRKYpdhARA0eIyk2JYOXr8gzWEBA6x
"""

!pip install ultralytics

from ultralytics import YOLO

# Load a COCO-pretrained YOLO12n model
model = YOLO("yolo12n.pt")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="coco8.yaml", epochs=100, imgsz=640)

#Run inference with the YOLO12n model on the 'bus.jpg' image
results = model("/content/TEST_000.jpg",save=True)